import type {
  Workspace,
  Member,
  Issue,
  Doc,
  Project,
  Notification,
  ActivityItem,
  SprintData,
  WeeklyBreakdown,
  MemberWorkload,
  HeatmapData,
  BurndownData,
  ApiKey,
} from './types';

export const WORKSPACES: Workspace[] = [
  {
    id: 'ws-1',
    name: 'Acme Corp',
    slug: 'acme-corp',
    plan: 'pro',
    memberCount: 12,
  },
  {
    id: 'ws-2',
    name: 'Design Studio',
    slug: 'design-studio',
    plan: 'free',
    memberCount: 4,
  },
  {
    id: 'ws-3',
    name: 'Open Source',
    slug: 'open-source',
    plan: 'free',
    memberCount: 28,
  },
];

export const MEMBERS: Member[] = [
  {
    id: 'm-1',
    name: 'Alex Chen',
    email: 'alex@acme.com',
    avatar: 'https://i.pravatar.cc/40?img=1',
    role: 'admin',
    joinedAt: '2024-01-15',
    lastActive: '2026-06-06',
    issuesAssigned: 8,
  },
  {
    id: 'm-2',
    name: 'Priya Sharma',
    email: 'priya@acme.com',
    avatar: 'https://i.pravatar.cc/40?img=5',
    role: 'member',
    joinedAt: '2024-02-01',
    lastActive: '2026-06-05',
    issuesAssigned: 5,
  },
  {
    id: 'm-3',
    name: 'Marcus Webb',
    email: 'marcus@acme.com',
    avatar: 'https://i.pravatar.cc/40?img=3',
    role: 'member',
    joinedAt: '2024-03-10',
    lastActive: '2026-06-06',
    issuesAssigned: 11,
  },
  {
    id: 'm-4',
    name: 'Sofia Reyes',
    email: 'sofia@acme.com',
    avatar: 'https://i.pravatar.cc/40?img=9',
    role: 'member',
    joinedAt: '2024-04-22',
    lastActive: '2026-06-04',
    issuesAssigned: 6,
  },
  {
    id: 'm-5',
    name: 'James Okafor',
    email: 'james@acme.com',
    avatar: 'https://i.pravatar.cc/40?img=7',
    role: 'viewer',
    joinedAt: '2024-05-01',
    lastActive: '2026-06-03',
    issuesAssigned: 2,
  },
  {
    id: 'm-6',
    name: 'Yuki Tanaka',
    email: 'yuki@acme.com',
    avatar: 'https://i.pravatar.cc/40?img=25',
    role: 'member',
    joinedAt: '2024-06-15',
    lastActive: '2026-06-06',
    issuesAssigned: 9,
  },
];

export const CURRENT_USER = MEMBERS[0];

export const PROJECTS: Project[] = [
  {
    id: 'p-1',
    name: 'Platform Core',
    description: 'Core infrastructure and API development',
    color: '#5b5ef4',
    icon: 'Zap',
    memberIds: ['m-1', 'm-2', 'm-3'],
    openIssues: 14,
    docCount: 8,
    progress: 62,
    lastActivity: '2026-06-06T09:30:00Z',
    workspaceId: 'ws-1',
  },
  {
    id: 'p-2',
    name: 'Design System',
    description: 'Component library and design tokens',
    color: '#30a46c',
    icon: 'Palette',
    memberIds: ['m-1', 'm-4', 'm-6'],
    openIssues: 7,
    docCount: 12,
    progress: 78,
    lastActivity: '2026-06-05T15:00:00Z',
    workspaceId: 'ws-1',
  },
  {
    id: 'p-3',
    name: 'Mobile App',
    description: 'iOS and Android client application',
    color: '#e5484d',
    icon: 'Smartphone',
    memberIds: ['m-2', 'm-3', 'm-5'],
    openIssues: 21,
    docCount: 5,
    progress: 34,
    lastActivity: '2026-06-06T11:00:00Z',
    workspaceId: 'ws-1',
  },
  {
    id: 'p-4',
    name: 'Analytics Engine',
    description: 'Data pipeline and reporting infrastructure',
    color: '#f59e0b',
    icon: 'BarChart2',
    memberIds: ['m-1', 'm-3', 'm-6'],
    openIssues: 9,
    docCount: 6,
    progress: 51,
    lastActivity: '2026-06-04T08:00:00Z',
    workspaceId: 'ws-1',
  },
];

export const ISSUES: Issue[] = [
  {
    id: 'i-1',
    identifier: 'CS-01',
    title: 'Authentication flow breaks on mobile Safari',
    description: 'Users on iOS Safari 17+ experience a redirect loop during OAuth login.',
    status: 'in_progress',
    priority: 'urgent',
    assignee: MEMBERS[2],
    labels: ['bug', 'auth'],
    projectId: 'p-1',
    dueDate: '2026-06-10',
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-06-05T14:00:00Z',
  },
  {
    id: 'i-2',
    identifier: 'CS-02',
    title: 'Implement dark mode for dashboard charts',
    description: 'Charts need to respect the current theme setting and update dynamically.',
    status: 'todo',
    priority: 'high',
    assignee: MEMBERS[1],
    labels: ['feature', 'ui'],
    projectId: 'p-2',
    dueDate: '2026-06-15',
    createdAt: '2026-05-22T09:00:00Z',
    updatedAt: '2026-06-04T16:00:00Z',
  },
  {
    id: 'i-3',
    identifier: 'CS-03',
    title: 'API rate limiting returns 500 instead of 429',
    description: 'When rate limit is exceeded, the server throws a 500 error.',
    status: 'in_review',
    priority: 'high',
    assignee: MEMBERS[0],
    labels: ['bug', 'api'],
    projectId: 'p-1',
    dueDate: '2026-06-08',
    createdAt: '2026-05-25T11:00:00Z',
    updatedAt: '2026-06-06T08:00:00Z',
  },
  {
    id: 'i-4',
    identifier: 'CS-04',
    title: 'Add CSV export to analytics reports',
    description: 'Users need to download report data for offline analysis.',
    status: 'backlog',
    priority: 'medium',
    assignee: MEMBERS[5],
    labels: ['feature', 'analytics'],
    projectId: 'p-4',
    dueDate: '2026-07-01',
    createdAt: '2026-05-28T13:00:00Z',
    updatedAt: '2026-05-30T10:00:00Z',
  },
  {
    id: 'i-5',
    identifier: 'CS-05',
    title: 'Push notification delivery delays on Android',
    description: 'Android notifications are delayed by 5-10 minutes.',
    status: 'todo',
    priority: 'urgent',
    assignee: MEMBERS[2],
    labels: ['bug', 'mobile'],
    projectId: 'p-3',
    dueDate: '2026-06-09',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-05T12:00:00Z',
  },
  {
    id: 'i-6',
    identifier: 'CS-06',
    title: 'Refactor token refresh logic',
    description: 'Current token refresh creates race conditions in concurrent requests.',
    status: 'in_progress',
    priority: 'high',
    assignee: MEMBERS[0],
    labels: ['refactor', 'auth'],
    projectId: 'p-1',
    dueDate: '2026-06-12',
    createdAt: '2026-06-02T10:00:00Z',
    updatedAt: '2026-06-06T09:00:00Z',
  },
  {
    id: 'i-7',
    identifier: 'CS-07',
    title: 'Design new onboarding flow screens',
    description: 'Update the onboarding experience for new users.',
    status: 'done',
    priority: 'medium',
    assignee: MEMBERS[3],
    labels: ['design', 'ux'],
    projectId: 'p-2',
    createdAt: '2026-05-10T09:00:00Z',
    updatedAt: '2026-06-03T17:00:00Z',
  },
  {
    id: 'i-8',
    identifier: 'CS-08',
    title: 'Set up CI/CD for mobile builds',
    description: 'Automate iOS and Android builds on each PR.',
    status: 'in_progress',
    priority: 'medium',
    assignee: MEMBERS[1],
    labels: ['devops', 'mobile'],
    projectId: 'p-3',
    dueDate: '2026-06-20',
    createdAt: '2026-06-03T11:00:00Z',
    updatedAt: '2026-06-06T07:00:00Z',
  },
  {
    id: 'i-9',
    identifier: 'CS-09',
    title: 'Button component accessibility audit',
    description: 'Review and fix ARIA labels, focus states, and keyboard nav.',
    status: 'todo',
    priority: 'low',
    assignee: MEMBERS[3],
    labels: ['a11y', 'ui'],
    projectId: 'p-2',
    dueDate: '2026-06-30',
    createdAt: '2026-06-04T14:00:00Z',
    updatedAt: '2026-06-04T14:00:00Z',
  },
  {
    id: 'i-10',
    identifier: 'CS-10',
    title: 'Database query optimization for reports',
    description: 'Report generation queries take >10s on large datasets.',
    status: 'backlog',
    priority: 'high',
    assignee: MEMBERS[5],
    labels: ['performance', 'backend'],
    projectId: 'p-4',
    dueDate: '2026-07-15',
    createdAt: '2026-06-05T09:00:00Z',
    updatedAt: '2026-06-05T09:00:00Z',
  },
  {
    id: 'i-11',
    identifier: 'CS-11',
    title: 'Add Slack integration for notifications',
    description: 'Send alerts to Slack channels when issues are created or updated.',
    status: 'backlog',
    priority: 'medium',
    assignee: MEMBERS[4],
    labels: ['integration', 'feature'],
    projectId: 'p-1',
    dueDate: '2026-07-20',
    createdAt: '2026-06-05T10:00:00Z',
    updatedAt: '2026-06-05T10:00:00Z',
  },
  {
    id: 'i-12',
    identifier: 'CS-12',
    title: 'Memory leak in real-time sync service',
    description: 'Long-running connections slowly increase memory consumption.',
    status: 'in_progress',
    priority: 'urgent',
    assignee: MEMBERS[2],
    labels: ['bug', 'performance'],
    projectId: 'p-1',
    dueDate: '2026-06-07',
    createdAt: '2026-06-06T06:00:00Z',
    updatedAt: '2026-06-06T10:00:00Z',
  },
  {
    id: 'i-13',
    identifier: 'CS-13',
    title: 'Typography token cleanup',
    description: 'Consolidate font-size and weight tokens in design system.',
    status: 'done',
    priority: 'low',
    assignee: MEMBERS[3],
    labels: ['design', 'cleanup'],
    projectId: 'p-2',
    createdAt: '2026-05-15T09:00:00Z',
    updatedAt: '2026-06-01T12:00:00Z',
  },
  {
    id: 'i-14',
    identifier: 'CS-14',
    title: 'Implement offline mode for mobile',
    description: 'Cache data locally so the app works without network.',
    status: 'todo',
    priority: 'medium',
    assignee: MEMBERS[1],
    labels: ['feature', 'mobile'],
    projectId: 'p-3',
    dueDate: '2026-08-01',
    createdAt: '2026-06-06T07:00:00Z',
    updatedAt: '2026-06-06T07:00:00Z',
  },
  {
    id: 'i-15',
    identifier: 'CS-15',
    title: 'Add webhook support to analytics events',
    description: 'Allow external systems to subscribe to analytics events via webhooks.',
    status: 'backlog',
    priority: 'low',
    assignee: MEMBERS[5],
    labels: ['feature', 'analytics', 'api'],
    projectId: 'p-4',
    dueDate: '2026-08-15',
    createdAt: '2026-06-06T08:00:00Z',
    updatedAt: '2026-06-06T08:00:00Z',
  },
];

export const DOCS: Doc[] = [
  {
    id: 'd-1',
    title: 'Platform Architecture Overview',
    content: 'architecture-overview',
    projectId: 'p-1',
    authorId: 'm-1',
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-06-05T14:00:00Z',
    collaborators: [MEMBERS[0], MEMBERS[1], MEMBERS[2]],
  },
  {
    id: 'd-2',
    title: 'API Reference Guide',
    content: 'api-reference',
    projectId: 'p-1',
    authorId: 'm-2',
    createdAt: '2026-04-15T09:00:00Z',
    updatedAt: '2026-06-06T08:00:00Z',
    collaborators: [MEMBERS[1], MEMBERS[0]],
  },
  {
    id: 'd-3',
    title: 'Design Token Specification',
    content: 'design-tokens',
    projectId: 'p-2',
    authorId: 'm-4',
    createdAt: '2026-05-01T11:00:00Z',
    updatedAt: '2026-06-04T16:00:00Z',
    collaborators: [MEMBERS[3], MEMBERS[5]],
  },
  {
    id: 'd-4',
    title: 'Component Library Guidelines',
    content: 'component-guidelines',
    projectId: 'p-2',
    authorId: 'm-4',
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-06-03T11:00:00Z',
    collaborators: [MEMBERS[3], MEMBERS[0]],
  },
  {
    id: 'd-5',
    title: 'Mobile Release Checklist',
    content: 'mobile-checklist',
    projectId: 'p-3',
    authorId: 'm-2',
    createdAt: '2026-05-20T09:00:00Z',
    updatedAt: '2026-06-06T09:00:00Z',
    collaborators: [MEMBERS[1], MEMBERS[2]],
  },
  {
    id: 'd-6',
    title: 'Analytics Data Dictionary',
    content: 'data-dictionary',
    projectId: 'p-4',
    authorId: 'm-6',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-05T15:00:00Z',
    collaborators: [MEMBERS[5], MEMBERS[0]],
  },
  {
    id: 'd-7',
    title: 'Authentication Security Policy',
    content: 'auth-security',
    projectId: 'p-1',
    authorId: 'm-1',
    createdAt: '2026-06-02T11:00:00Z',
    updatedAt: '2026-06-06T07:00:00Z',
    collaborators: [MEMBERS[0], MEMBERS[2]],
  },
  {
    id: 'd-8',
    title: 'Sprint Retrospective Template',
    content: 'retro-template',
    projectId: 'p-1',
    authorId: 'm-1',
    createdAt: '2026-06-05T14:00:00Z',
    updatedAt: '2026-06-06T08:00:00Z',
    collaborators: [MEMBERS[0]],
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'n-1',
    type: 'assignment',
    actor: MEMBERS[2],
    target: 'CS-12',
    targetType: 'issue',
    targetId: 'i-12',
    message: 'assigned you to CS-12 Memory leak in real-time sync service',
    read: false,
    createdAt: '2026-06-06T10:00:00Z',
  },
  {
    id: 'n-2',
    type: 'comment',
    actor: MEMBERS[1],
    target: 'CS-03',
    targetType: 'issue',
    targetId: 'i-3',
    message: 'commented on CS-03 API rate limiting',
    read: false,
    createdAt: '2026-06-06T09:30:00Z',
  },
  {
    id: 'n-3',
    type: 'status_change',
    actor: MEMBERS[0],
    target: 'CS-07',
    targetType: 'issue',
    targetId: 'i-7',
    message: 'moved CS-07 to Done',
    read: false,
    createdAt: '2026-06-05T17:00:00Z',
  },
  {
    id: 'n-4',
    type: 'mention',
    actor: MEMBERS[3],
    target: 'Platform Architecture Overview',
    targetType: 'doc',
    targetId: 'd-1',
    message: 'mentioned you in Platform Architecture Overview',
    read: true,
    createdAt: '2026-06-05T14:00:00Z',
  },
  {
    id: 'n-5',
    type: 'comment',
    actor: MEMBERS[5],
    target: 'CS-10',
    targetType: 'issue',
    targetId: 'i-10',
    message: 'commented on CS-10 Database query optimization',
    read: true,
    createdAt: '2026-06-05T11:00:00Z',
  },
  {
    id: 'n-6',
    type: 'assignment',
    actor: MEMBERS[0],
    target: 'CS-14',
    targetType: 'issue',
    targetId: 'i-14',
    message: 'assigned you to CS-14 Implement offline mode',
    read: true,
    createdAt: '2026-06-04T09:00:00Z',
  },
  {
    id: 'n-7',
    type: 'status_change',
    actor: MEMBERS[2],
    target: 'CS-01',
    targetType: 'issue',
    targetId: 'i-1',
    message: 'moved CS-01 to In Progress',
    read: true,
    createdAt: '2026-06-03T16:00:00Z',
  },
];

export const ACTIVITY_FEED: ActivityItem[] = [
  {
    id: 'a-1',
    type: 'status_change',
    actor: MEMBERS[2],
    target: 'CS-01',
    targetType: 'issue',
    targetId: 'i-1',
    description: 'moved CS-01 from Todo to In Progress',
    createdAt: '2026-06-06T10:30:00Z',
  },
  {
    id: 'a-2',
    type: 'comment',
    actor: MEMBERS[1],
    target: 'API Reference Guide',
    targetType: 'doc',
    targetId: 'd-2',
    description: 'commented on API Reference Guide',
    createdAt: '2026-06-06T09:45:00Z',
  },
  {
    id: 'a-3',
    type: 'create',
    actor: MEMBERS[0],
    target: 'CS-12',
    targetType: 'issue',
    targetId: 'i-12',
    description: 'created issue CS-12 Memory leak in real-time sync',
    createdAt: '2026-06-06T08:00:00Z',
  },
  {
    id: 'a-4',
    type: 'edit',
    actor: MEMBERS[3],
    target: 'Design Token Specification',
    targetType: 'doc',
    targetId: 'd-3',
    description: 'edited Design Token Specification',
    createdAt: '2026-06-05T16:00:00Z',
  },
  {
    id: 'a-5',
    type: 'status_change',
    actor: MEMBERS[0],
    target: 'CS-07',
    targetType: 'issue',
    targetId: 'i-7',
    description: 'closed CS-07 Design new onboarding flow',
    createdAt: '2026-06-05T15:00:00Z',
  },
  {
    id: 'a-6',
    type: 'assignment',
    actor: MEMBERS[0],
    target: 'CS-06',
    targetType: 'issue',
    targetId: 'i-6',
    description: 'assigned CS-06 to themselves',
    createdAt: '2026-06-05T11:00:00Z',
  },
  {
    id: 'a-7',
    type: 'create',
    actor: MEMBERS[5],
    target: 'Analytics Data Dictionary',
    targetType: 'doc',
    targetId: 'd-6',
    description: 'created Analytics Data Dictionary',
    createdAt: '2026-06-05T10:00:00Z',
  },
  {
    id: 'a-8',
    type: 'comment',
    actor: MEMBERS[2],
    target: 'CS-08',
    targetType: 'issue',
    targetId: 'i-8',
    description: 'commented on CS-08 CI/CD setup',
    createdAt: '2026-06-04T17:00:00Z',
  },
];

export const VELOCITY_DATA: SprintData[] = [
  { sprint: 'S1', closed: 8, opened: 12 },
  { sprint: 'S2', closed: 11, opened: 9 },
  { sprint: 'S3', closed: 14, opened: 10 },
  { sprint: 'S4', closed: 10, opened: 13 },
  { sprint: 'S5', closed: 16, opened: 8 },
  { sprint: 'S6', closed: 13, opened: 11 },
  { sprint: 'S7', closed: 18, opened: 9 },
  { sprint: 'S8', closed: 15, opened: 10 },
];

export const WEEKLY_BREAKDOWN: WeeklyBreakdown[] = [
  { week: 'Apr 28', urgent: 3, high: 5, medium: 8, low: 4 },
  { week: 'May 5', urgent: 2, high: 7, medium: 6, low: 5 },
  { week: 'May 12', urgent: 4, high: 4, medium: 9, low: 3 },
  { week: 'May 19', urgent: 1, high: 8, medium: 7, low: 6 },
  { week: 'May 26', urgent: 3, high: 6, medium: 5, low: 4 },
  { week: 'Jun 2', urgent: 5, high: 5, medium: 8, low: 2 },
];

export const MEMBER_WORKLOAD: MemberWorkload[] = [
  { member: MEMBERS[0], openIssues: 8, inProgress: 3, completedThisWeek: 4 },
  { member: MEMBERS[1], openIssues: 5, inProgress: 2, completedThisWeek: 2 },
  { member: MEMBERS[2], openIssues: 11, inProgress: 4, completedThisWeek: 3 },
  { member: MEMBERS[3], openIssues: 6, inProgress: 1, completedThisWeek: 5 },
  { member: MEMBERS[4], openIssues: 2, inProgress: 1, completedThisWeek: 1 },
  { member: MEMBERS[5], openIssues: 9, inProgress: 3, completedThisWeek: 2 },
];

export const BURNDOWN_DATA: BurndownData[] = [
  { day: 'Day 1', remaining: 42, ideal: 42 },
  { day: 'Day 2', remaining: 40, ideal: 38 },
  { day: 'Day 3', remaining: 37, ideal: 34 },
  { day: 'Day 4', remaining: 33, ideal: 30 },
  { day: 'Day 5', remaining: 31, ideal: 26 },
  { day: 'Day 6', remaining: 28, ideal: 22 },
  { day: 'Day 7', remaining: 24, ideal: 18 },
  { day: 'Day 8', remaining: 21, ideal: 14 },
  { day: 'Day 9', remaining: 18, ideal: 10 },
  { day: 'Day 10', remaining: 14, ideal: 6 },
  { day: 'Day 11', remaining: 11, ideal: 2 },
  { day: 'Day 12', remaining: 8, ideal: 0 },
];

export function generateHeatmapData(): HeatmapData[] {
  const data: HeatmapData[] = [];
  const now = new Date('2026-06-06');
  for (let i = 83; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    const dateStr = d.toISOString().split('T')[0];
    const dayOfWeek = d.getDay();
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
    const base = isWeekend ? 1 : 4;
    const count = Math.random() < 0.15 ? 0 : Math.floor(Math.random() * base + (isWeekend ? 0 : 1));
    data.push({ date: dateStr, count: Math.min(count, 8) });
  }
  return data;
}

export const HEATMAP_DATA = generateHeatmapData();

export const API_KEYS: ApiKey[] = [
  {
    id: 'key-1',
    name: 'Production API Key',
    key: 'cs_live_••••••••••••••••3f8a',
    createdAt: '2026-03-01T10:00:00Z',
    lastUsed: '2026-06-06T08:00:00Z',
  },
  {
    id: 'key-2',
    name: 'CI/CD Integration',
    key: 'cs_live_••••••••••••••••9d2c',
    createdAt: '2026-04-15T09:00:00Z',
    lastUsed: '2026-06-05T22:00:00Z',
  },
  {
    id: 'key-3',
    name: 'Development Key',
    key: 'cs_test_••••••••••••••••a1b4',
    createdAt: '2026-05-10T11:00:00Z',
    lastUsed: '2026-06-04T16:00:00Z',
  },
];
